### ISSUE TITLE
Code repository name

### ISSUE THREAD

**Issue by raortegar** [Neuronys/moodle-local_nolej#3]
Hello, 
According the Moodle documentation https://moodledev.io/general/community/plugincontribution/checklist#code-repository-name   

The repository name should use the standard frankenstyle Moodle naming convention which makes it easy for Moodle admins to identify your plugin.

The correct format to use is moodle-{plugintype}_{pluginname}. For example,  if your plugin was "mod_attendance" the correct name to use would be: "moodle-mod_attendance"

In this case the name should ne moodle-local_nolej

Thanks

**Comment by padvincenzo** [comment]
Plugin name updated
